/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddStoryRouteImport } from './routes/add-story'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddStoryRoute = AddStoryRouteImport.update({
  id: '/add-story',
  path: '/add-story',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-story': typeof AddStoryRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tools': typeof ToolsRoute
  '/chat/$id': typeof ChatIdRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-story': typeof AddStoryRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tools': typeof ToolsRoute
  '/chat/$id': typeof ChatIdRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-story': typeof AddStoryRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tools': typeof ToolsRoute
  '/chat/$id': typeof ChatIdRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-story'
    | '/admin'
    | '/auth'
    | '/calls'
    | '/chats'
    | '/discover'
    | '/home'
    | '/profile'
    | '/settings'
    | '/status'
    | '/tools'
    | '/chat/$id'
    | '/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-story'
    | '/admin'
    | '/auth'
    | '/calls'
    | '/chats'
    | '/discover'
    | '/home'
    | '/profile'
    | '/settings'
    | '/status'
    | '/tools'
    | '/chat/$id'
    | '/story/$id'
  id:
    | '__root__'
    | '/'
    | '/add-story'
    | '/admin'
    | '/auth'
    | '/calls'
    | '/chats'
    | '/discover'
    | '/home'
    | '/profile'
    | '/settings'
    | '/status'
    | '/tools'
    | '/chat/$id'
    | '/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddStoryRoute: typeof AddStoryRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CallsRoute: typeof CallsRoute
  ChatsRoute: typeof ChatsRoute
  DiscoverRoute: typeof DiscoverRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  ToolsRoute: typeof ToolsRoute
  ChatIdRoute: typeof ChatIdRoute
  StoryIdRoute: typeof StoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-story': {
      id: '/add-story'
      path: '/add-story'
      fullPath: '/add-story'
      preLoaderRoute: typeof AddStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddStoryRoute: AddStoryRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CallsRoute: CallsRoute,
  ChatsRoute: ChatsRoute,
  DiscoverRoute: DiscoverRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  ToolsRoute: ToolsRoute,
  ChatIdRoute: ChatIdRoute,
  StoryIdRoute: StoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
